title: Dr.Xama---RPG-MAKER-MV
description: Todos meus trabalhos para o RPG MAKER MV.
show_downloads: true
google_analytics:
theme: jekyll-theme-slate
plugins:
  DrXama_MVDebug: https://raw.githubusercontent.com/GS-GAME-WORDS/Dr.Xama---RPG-MAKER-MV/master/plugins/DrXama_MVDebug.js